### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sang-codecademy** [plaflin/Murder_Mystery#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ No syntax errors. Great job writing all valid Python code without any errors or issues!
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ You implemented the functions successfully. Great job finding the correct person at the end.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4/4
* _Comment(s):_ Great job defining and naming classes and functions. Everything was written correctly and you simplified you code as much as possible. You also effectively refactored your code so that a single function doesn't try to do everything, such as with your percent_difference, etc. functions.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4/4
* _Comment(s):_ Your knowledge of Python and general computing is very apparent in your code. You consistently used Python language features where appropriate.
 
### Overall Score: 16/16
Overall you did a fantastic job on this project! I can tell that you have learned a lot from the PWP course and hope you continue on with your Python journey.

**Comment by plaflin** [comment]
Thank you for the kind words.
